config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    root :to => 'devise/sessions#new'
  end

  resources :games do
    resources :players
    resources :tiles
    resource :words
    post 'start'
    post 'refresher'
  end

end

app/models/game.rb
class Game < ActiveRecord::Base
  has_many :tiles, dependent: :destroy 
  has_many :players, dependent: :destroy
  belongs_to :winner, class_name: "Player"

  def deal_tiles!
    transaction do
      2.times { tiles.create! }
    end
  end

  def available_tiles
    tiles.map(&:value).sort
  end

  def start!
    transaction do
      update!(started: true)
      deal_initial_tiles!
    end
  end
  
  def finish_and_assign_winner!(winning_player)
    self.finished = true
    self.winner = winning_player
    save!
  end

  def advance_stage!(player)
    if all_tiles_used?
      finish_and_assign_winner!(player) 
    else
      deal_tiles!
    end
  end

  private
  def all_tiles_used?
    tiles.count >= max_tile_count
  end

  def deal_initial_tiles!
    12.times { tiles.create! }
  end
end

app/models/player.rb
class Player < ActiveRecord::Base
  belongs_to :game
  belongs_to :user
  has_many :words, dependent: :destroy

  validates :game_id, :user_id, presence: true

  def advance_stage!
    game.advance_stage!(self)
  end

  def submission_correct?
    all_words_valid? && uses_all_tiles?
  end

  private 

  def all_words_valid?
    words.all? { |word| word.exists? }
  end

  def uses_all_tiles?
    tiles_used_in_words == game.available_tiles
  end

  def tiles_used_in_words
    words.flat_map do |word|
      word.string.gsub('qu', '*').chars.map { |letter| letter == '*' ? 'qu' : letter }
    end.sort
  end
end

app/models/tile.rb
class Tile < ActiveRecord::Base
   LETTER_FREQUENCIES = {
    'a' => 63693,
    'b' => 11853,
    'c' => 13825,
    'd' => 32252,
    'e' => 88494,
    'f' => 13126,
    'g' => 16072,
    'h' => 35514,
    'i' => 35389,
    'j' => 2714,
    'k' => 11422,
    'l' => 35218,
    'm' => 17926,
    'n' => 46774,
    'o' => 53892,
    'p' => 11087,
    'qu' => 1743,
    'r' => 34450,
    's' => 39709,
    't' => 72232,
    'u' => 23040,
    'v' => 8510,
    'w' => 19149,
    'x' => 1994,
    'y' => 19439,
    'z' => 1361}

  belongs_to :game
  validates :value, presence: true, inclusion: { in: LETTER_FREQUENCIES }
  before_validation :assign_random_letter_to_value

  private

  def assign_random_letter_to_value
    self.value ||= random_letter
  end

  def random_letter
    random_number = rand(LETTER_FREQUENCIES.values.sum)
    LETTER_FREQUENCIES.detect do |key,value| 
      random_number -= value
      random_number + value < value 
    end[0]
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :players, dependent: :destroy
  has_many :games, through: :players
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/models/word.rb
class Word < ActiveRecord::Base
  DICTIONARY = Dictionary.from_file('public/dictionary.txt')

  belongs_to :player

  validates :string, length: { minimum: 1 }

  def exists?
    DICTIONARY.exists?(string)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def after_sign_in_path_for(user)
    games_path
  end

  def after_sign_out_path_for(user)
    new_user_session_path
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_filter :user_logged_in?

  def index
    @games = Game.where(started: false)
  end

  def new
  end

  def create
    @game = CreateGame.new.make(current_user)
    redirect_to @game
  end

  def show
    @game = Game.find(params[:id])
    @player = @game.players.where(user: current_user).first
    @players_emails = @game.players.map{ |player| player.user.email }

    if @game.finished?
      render 'finished'
    elsif @game.started?
      render 'two_up'
    else
      render 'pending'
    end
  end

  def start
    @game = Game.find(params[:game_id])
    @game.start!

    redirect_to @game
  end

  def refresher
    @game = Game.find(params[:gameId])
    if @game.finished || @game.started.to_s != params[:started]
      render json: {actionRequired: 'reload'}
    elsif @game.tiles.count != params[:tileCount].to_i
      tiles = tiles_to_add(@game, @game.tiles.count, params[:tileCount].to_i)
      render json: { actionRequired: 'addTiles', tiles: tiles }
    else
      render json: { actionRequired: 'none' }
    end
  end

  private

  def user_logged_in?
    redirect_to new_user_session_path if !user_signed_in?
  end

  def refresh_required?
    params[:tileCount].to_i != @game.tiles.count
  end

  def tiles_to_add(game, game_tile_count, current_view_tile_count)
    number_of_tiles_to_add = (game_tile_count - current_view_tile_count)
    tiles = game.tiles.last(number_of_tiles_to_add).map(& :value)
    tiles
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  def create
    @player = Player.create!(game_id: player_params, user: current_user)
    redirect_to game_path(@player.game)
  end

  private

  def player_params
    params.require(:game_id)
  end

end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  def create
    game = Game.find(params[:game_id])
    player = game.players.where(user_id: current_user).first!
    words = params[:words]

    begin
      submission = CreateSubmission.new(player, words)
      result = submission.make!
      render json: {
        submissionResult: result,
        letters: game.tiles.last(2).map(& :value),
      }
    rescue Exception => e
      render json: {
        submissionResult: "save failure",
        errorMessage: "#{e.message}"
      }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/games_helper.rb
module GamesHelper
  def user_emails(game)
    game.players.map{ |player| player.user.email}.join(", ")
  end

  def winning_words(game)
    game.winner.words.pluck(:string).join(", ")
  end
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/games/_pending.html.erb
<div class="pending">
<h1>Waiting for Game to Commence</h1>
<h2>Players in this game: <% @game.players.each do |player| %><%= player.user.email %>, <% end %></h2>

<%= button_to "Start Game Now", { action: "start", method: "post", game_id: @game.id }, {class: 'myButton btn-small'} %>
</div>

app/views/games/_two_up.html.erb
<div class="leftside">

  <h1>Game in Progress</h1>
  <h2>You are playing with: <% @game.players.each do |player| %><%= player.user.email %><% end %></h2>
  <div class="submission-message">
  </div>
  <h2>Your Tiles</h2><br>
  <div class="pile">
    <% @game.tiles.each do |tile| %>
      <div class="tile"><%= tile.value %></div>
    <% end %>
  </div>

  <div class="twoup-container">
    <button type="button", class=" twoupbutton myButton btn-small">Two Up!</button>
    <%=link_to "Leave Game", games_path %>
  </div>
</div>

<div class="rightside">
  <div class="wordbox">
    <div class="word">
    </div>
    <div class="word">
    </div>
    <div class="word">
    </div>
    <div class="word">
    </div>
    <div class="word">
    </div>
     <div class="word">
    </div>
    <div class="word">
    </div>
    <div class="word">
    </div>
    <div class="word">
    </div>
    <div class="word">
    </div>
  </div>
</div>

app/views/games/_variables.html.erb
<% content_for :head do %>
  <%= tag :meta, name: "gameid", content: @game.id %>
  <%= tag :meta, name: "finished", content: @game.finished? %>
  <%= tag :meta, name: "started", content: @game.started? %>
<% end %>

app/views/games/finished.html.erb
<div class="pending">
  <h1>Game Finished!</h1>

  <h2><%= @game.winner.user.email %> Has won the Game!</h2>

  <b>The Winning words were:</b>
  <%= winning_words(@game) %><br>

  <%= button_to "Back to Lobby", games_path, method: "get", :class => "myButton" %>
</div>

app/views/games/index.html.erb
<% content_for :head do %>
  <meta http-equiv="refresh" content="5">
<% end %> 
<div id="index">
  <h1>Available Games</h1>

  <% @games.each do |game| %>
    <div class="game-name">
      Game started by: <%= game.players.first.user.email %>
    </div>
    
    <%= button_to("Join Game", game_players_path(game), method: "post", :class=> "myButton small-button joingame") %>

  <% end %>

  <br>

  <%= button_to("Create new game", games_path, method: "post", :class=> "myButton") %>
</div>

app/views/games/pending.html.erb
<%= render 'variables' %>

<div class="pending">
  <h1>Waiting for Game to Commence</h1>
  <h2>Players in this game: <%= user_emails(@game) %></h2> 

  <%= button_to "Start Game Now", { action: "start", method: "post", game_id: @game.id }, {class: 'myButton btn-small'} %>
</div>

app/views/games/show.html.erb
<% content_for :head do %>
  <meta name="gameid" content="<%= @game.id %>">
  <meta name="finished" content="<%= @game.finished? %>">
  <meta name="started" content="<%= @game.started? %>">
<% end %>


<% if !@game.started? %>
<%= render partial: 'pending' %>
<% else %>
<%= render partial: 'two_up' %>
<% end %>


<script>
  start();
</script>

app/views/games/two_up.html.erb
<%= render "variables" %>

<div class="leftside">
  <h1>Game in Progress</h1>
  <h2>You are playing with: <%= user_emails(@game) %></h2>
  <div class="submission-message">
  </div>
  <h2>Your Tiles</h2><br>
  <div class="pile">
    <% @game.tiles.each do |tile| %>
      <div class="tile"><%= tile.value %></div>
    <% end %>
  </div>

  <div class="twoup-container">
    <button type="button", class=" twoupbutton myButton btn-small">Two Up!</button>
    <%=link_to "Leave Game", games_path %>
  </div>
</div>


<div class="rightside">
  <div class="wordbox">
    <% 10.times do %>
      <div class="word">
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TwoUp</title>
  <%= yield :head %> 
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body id="<%= "#{params[:controller]}-#{params[:action]}" %>">
  <div id="header">
    <% if user_signed_in? %>
      <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to "Sign in!", new_user_session_path %>
    <% end %>
  </div>

  <div class="container">
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </div>
</body>
</html>